name: cnn_flutter_module
description: A new flutter module project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#
# This version is used _only_ for the Runner app, which is used if you just do
# a `flutter run` or a `flutter make-host-app-editable`. It has no impact
# on any other native host app that you embed your Flutter project into.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # Awesome 图标库
  # https://github.com/fluttercommunity/font_awesome_flutter
  font_awesome_flutter: ^9.1.0
  # 权限判断
#  permission_handler: ^8.1.6
  # 图片缓存及加载
  # extended_image: ^1.2.0

  # 图片选择器
  image_picker: ^0.8.4+2

  # 网络
  # 网络判断
  connectivity: ^3.0.6
  dio: ^4.0.0
  dio_log: ^2.0.1
  dio_cookie_manager: ^2.0.0

  # 加密 https://pub.dev/packages/encrypt
  encrypt: ^5.0.1
  # 吐司提示
  fluttertoast: ^8.0.8
 
  # 广播机制，用以跨页面事件通知，用event_bus提供的事件总线功能来实现一些状态的更新
  # https://pub.flutter-io.cn/packages/event_bus#-example-tab-
  event_bus: ^2.0.0
  # 状态管理
  # https://pub.flutter-io.cn/packages/provider#-example-tab-
  # provider: ^6.0.1
  # GetX 是 Flutter 上的一个轻量且强大的解决方案：高性能的状态管理、智能的依赖注入和便捷的路由管理。
  # https://github.com/jonataslaw/getx/blob/master/README.zh-cn.md#%E5%85%B3%E4%BA%8Eget
  # https://pub.dev/packages/get
#  get: ^4.3.8

  lottie: ^1.2.1

  waterfall_flow: ^3.0.1
  # 瀑布流布局
  flutter_staggered_grid_view: "^0.4.0"
  # flutter最强大的siwiper, 多种布局方式，无限轮播，Android和IOS双端适配.
  # https://github.com/serenader2014/flutter_carousel_slider
  carousel_slider: ^4.0.0
  # 获取控件位置尺寸
  # 利用RectGetter组件获取控件位置尺寸实现的几个高级效果和功能
  # https://juejin.im/post/5b6375f8e51d45190f4af4c2
  rect_getter: ^1.0.0
  # 处理键盘事件 https://github.com/diegoveloper/flutter_keyboard_actions
  keyboard_actions: ^3.4.4
  # #本地库引用 注意缩进格式
  # flutter_icu_common:
  #   path: ../../flutter_icu_common/flutter_icu_common/
  mpsf_framework:
    git:
      url: https://github.com/ZFlutter-Pub/mpsf-framework.git #git地址
      ref: main #分支名

  # 路由跳转框架
  fluro: ^2.0.3

  flutter_easyrefresh: ^2.2.1

  webview_flutter: ^2.1.1
  flutter_inappwebview: ^5.3.2

  url_launcher: ^6.0.12

  flutter_animated_dialog: ^2.0.1

  flutter_widget_from_html_core: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/datas/
    - assets/datas-mock/
    - assets/lottiefiles/
    - assets/images/
    - assets/images/account/
    - assets/images/else/
    - assets/images/error/
    - assets/images/guide/
    - assets/images/login/
    - assets/images/mainframe/
    - assets/images/order/
    - assets/images/order/dark/
    - assets/images/product/
    - assets/images/start/
    - assets/images/store/
    - assets/images/loading/
    - assets/images/home/
    - assets/images/news/
    - assets/images/discover/
    - assets/images/navigationBar/

    # - assets/images/2.0x/
    # - assets/images/3.0x/
    - assets/userful_images/
    - assets/htmls/
    - assets/htmls/product/
    - assets/htmls/product/70479667894_files/
  # To add Flutter specific assets to your application, add an assets section,
  # like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add Flutter specific custom fonts to your application, add a fonts
  # section here, in this "flutter" section. Each entry in this list should
  # have a "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: PoiretOne
      fonts:
        - asset: assets/fonts/PoiretOne-Regular.ttf
    - family: ZCOOLQingKeHuangYou
      fonts:
        - asset: assets/fonts/ZCOOLQingKeHuangYou-Regular.ttf

  # This section identifies your Flutter project as a module meant for
  # embedding in a native host app.  These identifiers should _not_ ordinarily
  # be changed after generation - they are used to ensure that the tooling can
  # maintain consistency when adding or modifying assets and plugins.
  # They also do not have any bearing on your native host application's
  # identifiers, which may be completely independent or the same as these.
  module:
    androidX: true
    androidPackage: com.example.cnn_flutter_module
    iosBundleIdentifier: com.example.cnnFlutterModule
